name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build, tag, and push Docker image to Docker Hub
      run: |
        cd newbackend
        docker build -t ethan929/guangqi:${{ github.sha }} .
        docker push ethan929/guangqi:${{ github.sha }}

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        # SSH into the EC2 instance, stop the current Docker container, and run the new one
        ssh -o StrictHostKeyChecking=no ec2-user@13.215.125.105 "\
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} && \
        docker pull ethan929/guangqi:${{ github.sha }} && \
        docker container stop nodejs || true && \
        docker container rm nodejs || true && \
        docker run -d --name nodejs -p 3080:3080 ethan929/guangqi:${{ github.sha }}"
